version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm run install:lambda
  build:
    commands:
      - npm run deploy:cert
  post_build:
    commands:
      - npm run test:remote
